# Generated by Django 3.1.2 on 2021-04-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Обновлено')),
                ('image', models.ImageField(blank=True, upload_to='post/', verbose_name='Изображение')),
                ('moder', models.BooleanField(default=False, verbose_name='Модерация')),
                ('slug', models.SlugField(default=models.CharField(max_length=256, verbose_name='Название'), unique=True)),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'db_table': 'post',
                'ordering': ['-published_at'],
            },
        ),
    ]
